- hosts: jenkins
  become: true
  tasks:
  - name: "Add user to group"
    user:
      name: jenkins
      group: docker
  - name: "python pip"
    apt:
      name: python3-pip
      state: latest
      update_cache: true
  - name: "docker sdk"
    pip:
     name: docker
  - name: Create Docker registry
    docker_container:
      name: registry
      image: registry:2
      exposed_ports: 5000:5000
      network_mode: host
